/** Curated Lucide icon names available for categories */
export const CATEGORY_ICONS = [
  'utensils',
  'coffee',
  'beer',
  'pizza',
  'car',
  'bus',
  'fuel',
  'plane',
  'home',
  'building-2',
  'shopping-bag',
  'shirt',
  'store',
  'clapperboard',
  'music',
  'gamepad-2',
  'heart-pulse',
  'stethoscope',
  'pill',
  'dumbbell',
  'receipt',
  'zap',
  'droplets',
  'wifi',
  'smartphone',
  'wrench',
  'graduation-cap',
  'book-open',
  'briefcase',
  'laptop',
  'gift',
  'hand-coins',
  'trending-up',
  'landmark',
  'banknote',
  'wallet',
  'piggy-bank',
  'credit-card',
  'baby',
  'paw-print',
  'palmtree',
  'tent',
  'repeat',
  'tag',
  'plus-circle',
  'circle-ellipsis',
  'circle',
] as const

export type CategoryIconName = (typeof CATEGORY_ICONS)[number]
