<script setup lang="ts">
import {
  Utensils,
  Car,
  Home,
  ShoppingBag,
  Clapperboard,
  HeartPulse,
  Receipt,
  GraduationCap,
  CircleEllipsis,
  Briefcase,
  Laptop,
  Gift,
  PlusCircle,
  Circle,
  Wallet,
  PiggyBank,
  CreditCard,
  Banknote,
  Plane,
  Bus,
  Fuel,
  Coffee,
  Beer,
  Pizza,
  Shirt,
  Dumbbell,
  Stethoscope,
  Pill,
  Baby,
  PawPrint,
  Smartphone,
  Wifi,
  Zap,
  Droplets,
  Wrench,
  Music,
  Gamepad2,
  BookOpen,
  Palmtree,
  Tent,
  Building2,
  Store,
  TrendingUp,
  HandCoins,
  Landmark,
  Repeat,
  Tag,
} from '@lucide/vue'
import { computed, type Component } from 'vue'

const props = withDefaults(
  defineProps<{
    name: string
    size?: number
  }>(),
  { size: 20 },
)

const map: Record<string, Component> = {
  utensils: Utensils,
  coffee: Coffee,
  beer: Beer,
  pizza: Pizza,
  car: Car,
  bus: Bus,
  fuel: Fuel,
  plane: Plane,
  home: Home,
  'building-2': Building2,
  'shopping-bag': ShoppingBag,
  shirt: Shirt,
  store: Store,
  clapperboard: Clapperboard,
  music: Music,
  'gamepad-2': Gamepad2,
  'heart-pulse': HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  dumbbell: Dumbbell,
  receipt: Receipt,
  zap: Zap,
  droplets: Droplets,
  wifi: Wifi,
  smartphone: Smartphone,
  wrench: Wrench,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  briefcase: Briefcase,
  laptop: Laptop,
  gift: Gift,
  'hand-coins': HandCoins,
  'trending-up': TrendingUp,
  landmark: Landmark,
  banknote: Banknote,
  wallet: Wallet,
  'piggy-bank': PiggyBank,
  'credit-card': CreditCard,
  baby: Baby,
  'paw-print': PawPrint,
  palmtree: Palmtree,
  tent: Tent,
  repeat: Repeat,
  tag: Tag,
  'plus-circle': PlusCircle,
  'circle-ellipsis': CircleEllipsis,
  circle: Circle,
}

const icon = computed(() => map[props.name] ?? Circle)
</script>

<template>
  <component :is="icon" :size="size" />
</template>
